# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'HelloSayer']

# Cell
def say_hello(to):
    """Say Hello to someone"""
    return f"Hello {to}!"

# Cell
class HelloSayer:
    """Say hello to `to` using `say_hello`"""
    def __init__(self, to):
        self.to = to

    def say(self):
        """Say hello using `say_hello`"""
        return say_hello(self.to)